version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: aerolineas_condor_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: aerolineas_condor_db
    ports:
      - "3306:3306"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password